# Generated by Django 4.1 on 2023-12-16 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user email')),
                ('money', models.IntegerField(default=100, verbose_name='my money')),
                ('win', models.IntegerField(default=0, verbose_name='my wins')),
                ('defeat', models.IntegerField(default=0, verbose_name='my defeats')),
            ],
            options={
                'verbose_name': 'game profile',
                'verbose_name_plural': 'game profiles',
            },
        ),
    ]
