# Generated by Django 4.1 on 2023-12-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user email')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='nickname')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='location')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='about you')),
                ('photo', models.ImageField(blank=True, default='profile_photo/default_user_profile_photo.png', null=True, upload_to='profile_photo/', verbose_name='profile photo')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
